filebeat.inputs:
  type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/app/logs/*
  tags: 'tester'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  enabled: true

setup.ilm.enabled: false
setup.template.overwrite: true
setup.template:
  name: 'tester'
  pattern: 'tester'
  enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl.verification_mode: "none"
  indices:
    - index: "tester"
      when.contains:
        tags: "tester"
setup.kibana:
  host: "http://kibana:5601"