name: filebeat

filebeat.inputs:
- type: filestream
  id: test-id
  paths:
    - "/usr/share/filebeat/logs/app/logs/*"
  tags: 'tester'

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.ilm.enabled: false
setup.template.overwrite: true
setup.template:
  name: 'tester'
  pattern: 'tester*'
  enabled: true

output.logstash:
  hosts: [ http://logstash:5044 ]
  indices:
    - index: "tester"
      when.contains:
        tags: "tester"

http:
  enabled: true
  host: 0.0.0.0