filebeat.inputs:
  type: log
  enabled: true
  paths:
    - /usr/share/filebeat/app/logs/*
  tags: 'tester'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.ilm.enabled: false
setup.template.overwrite: true
setup.template:
  name: 'tester'
  pattern: 'tester'
  enabled: true

output.logstash:
  hosts: ['logstash:5044']
  loadbalance: true
  indices:
    - index: "tester"
      when.contains:
        tags: "tester"
